CREATE TABLE "gigs" (
	"id" uuid PRIMARY KEY DEFAULT gen_random_uuid() NOT NULL,
	"kind" text NOT NULL,
	"category" text NOT NULL,
	"title" text NOT NULL,
	"poster_name" text NOT NULL,
	"poster_type" text NOT NULL,
	"location" text NOT NULL,
	"styles" json DEFAULT '[]',
	"when" text NOT NULL,
	"compensation" text NOT NULL,
	"deadline" date,
	"contact_email" text NOT NULL,
	"contact_url" text,
	"entity_url" text,
	"status" text DEFAULT 'open' NOT NULL,
	"dancer_id" uuid,
	"created_at" timestamp DEFAULT now(),
	"updated_at" timestamp DEFAULT now()
);
